<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Ricardos-MacBook-Pro.local" failures="1" tests="5" name="Regression Login - Linear" time="74.684" errors="0" timestamp="22 Jun 2024 17:47:49 GMT">
  <testcase classname="saucedemo.Login" name="test001" time="34.032">
    <failure type="java.lang.AssertionError" message="Validate users is logged successfully expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Validate users is logged successfully expected [true] but found [false]
at saucedemo.Login.test001(Login.java:60)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test001 -->
  <testcase classname="saucedemo.Login" name="test002" time="22.791"/>
  <testcase classname="saucedemo.Login" name="test003" time="17.625"/>
  <testcase classname="saucedemo.Login" name="test004" time="0.001"/>
  <testcase classname="saucedemo.Login" name="test005" time="0.0"/>
</testsuite> <!-- Regression Login - Linear -->
